### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by MrLoh** [TheSavior/react-native-mask-loader#2]
I love this. Also a huge fan of the twitter loading animation and though about how to build that before. So I was very excited about your article. Thanks for sharing. 

If I understand correctly this depends on the masked view that is iOS only though. Do you have any idea wether something similar is possible for android? 

Thanks again for sharing this code!!

**Comment by elicwhite** [comment]
MaskedViewiOS is iOS only as you pointed out. It was a community contribution by @skevy: https://twitter.com/skevy/status/954178302163300352.

It is possible to create this component on Android (although slightly more complex than the iOS equivalent since the android approach to masking is a bit more complicated.

Feel free to add support for this to RN core and then it can just be `MaskedView`. :)
