### ISSUE TITLE
Rendering question

### ISSUE THREAD

**Issue by kikoseijo** [TheSavior/react-native-mask-loader#4]
Im on simulator, IOS, and the animation leaves strange dirty thing around.
Just wondering if this is just because of the simulator or maybe the image im using. (them bellow)

Nice work btw.

![screen shot 2018-02-01 at 21 50 47](https://user-images.githubusercontent.com/1528668/35702666-fba164e6-0799-11e8-8ace-2475d0fd16ae.png)

![screen shot 2018-02-01 at 21 51 33](https://user-images.githubusercontent.com/1528668/35702713-1b61b20e-079a-11e8-9d20-3c04055aeba3.png)

**Comment by elicwhite** [comment]
Yeah, it looks like it is because of your image. We scale up the mask and expect that it fully reveals the app. 

If your mask has stuff in the middle then when it scales up those it will cover part of the app. 

It should be possible to hide the mask once it is done animating but it likely still won’t look good with this mask.
