### ISSUE TITLE
Are we required to do a large amount of setup, or can we simply use <Loader> for logic?

### ISSUE THREAD

**Issue by VicFrolov** [TheSavior/react-native-mask-loader#7]
Meaning, can I simply wrap my RootContainer like so:

```
        <Loader
          isLoaded={this.state.isLoaded}
          imageSource={Images.superDuperCoolPic}
          backgroundStyle={{ backgroundColor: 'red' }}
        >
          <RootContainer />
        </Loader>
```
and when isLoaded becomes true, it does all the animation? Because for me right now I get the full screen with my logo, but it never animates into the app when `this.state.isLoaded` becomes true

**Comment by elicwhite** [comment]
Yep. That should be all you need. Maybe check out the example if you are having trouble getting it set up.

**Comment by VicFrolov** [comment]
Yeah I got it working, and looks fantastic with twitter logo. Problem is our logo is a capital letter, so I guess the deadspace between it causes wonky animations near the end, any ideas for a fix for this :D? And it seems the width/height has to be very specific, what if we wanted the width of the image to be, say, 75% of the screen width?

**Comment by elicwhite** [comment]
The image size and style should probably be additional props to the component so that it can be customized to support your case. Perhaps there should just be a render prop that would be used here: https://github.com/TheSavior/react-native-mask-loader/blob/master/src/index.js#L93-L98

That API would also support people using SVGs instead of images. 

Want to take a stab at it and send a diff? :)

**Comment by VicFrolov** [comment]
Just made a small tiny PR, but I am going to be happy to take on this challenge! Busy at work for the time being but I promise I'll get around to it soon :D
